#include QMK_KEYBOARD_H
#include <stdio.h>
#include "leds.c"

#include "./keymap_dvorak_programmer_international.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
		DP_SCLN, DP_COMM, DP_DOT, DP_P, DP_Y,                           /**/    DP_F, DP_G, DP_C, DP_R, DP_L,
		ALGR_T(DP_A), LALT_T(DP_O), LCTL_T(DP_E), LSFT_T(DP_U), DP_I,   /**/    DP_D, LSFT_T(DP_H), LCTL_T(DP_T), LALT_T(DP_N), LGUI_T(DP_S),
		DP_QUOT, DP_Q, DP_J, DP_K, DP_X,                                /**/    DP_B, DP_M, DP_W, DP_V, DP_Z,
		XXXXXXX, XXXXXXX, XXXXXXX, DP_TAB, LT(2, DP_SPC),               /**/    LT(1, DP_BSPC), DP_ENT, XXXXXXX, XXXXXXX, XXXXXXX),

	[1] = LAYOUT(
		DP_LBRC, DP_LCBR, DP_RCBR, DP_LPRN, DP_EQL,                     /**/    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		ALGR_T(DP_DLR), DP_AMPR, XXXXXXX, LSFT_T(XXXXXXX), XXXXXXX,     /**/    UC_LINX, LSFT_T(DP_CCED), DP_TILD, DP_DACU, DP_DTIL,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                    /**/    XXXXXXX, XXXXXXX, XXXXXXX, KC_HOME, KC_INS,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, LT(3, DP_SPC),              /**/    DP_SPC, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX),

	[2] = LAYOUT(
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,           /**/    DP_ASTR, DP_RPRN, DP_PLUS, DP_RBRC, DP_EXLM,
		XXXXXXX, XXXXXXX, XXXXXXX, LSFT_T(XXXXXXX), XXXXXXX,   /**/    DP_HASH, LSFT_T(DP_SLSH), DP_AT, DP_BSLS, DP_MINS,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,           /**/    XXXXXXX, DP_DOWN, DP_UP, DP_LEFT, DP_RIGHT,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,           /**/    LT(4, DP_SPC), XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX),
	
	[3] = LAYOUT(
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,      /**/    DP_F10, DP_F2, DP_F4, DP_F6, DP_F8,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,      /**/    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,      /**/    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,      /**/    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX),

	[4] = LAYOUT(
		DP_F7, DP_F5, DP_F3, DP_F1, DP_F9,      /**/    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		QK_BOOT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,      /**/    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		UG_TOGG, UG_NEXT, UG_HUEU, UG_SATU, UG_VALU,      /**/    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, QK_BOOT,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,      /**/    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX),
};

// Custom hold-tap delay per key
uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
	case ALGR_T(DP_A):
		return 200;
	case LALT_T(DP_O):
		return 200;
	case LCTL_T(DP_E):
		return 200;
	case LSFT_T(DP_U):
		return 200;
        case LT(1, DP_SPC):
            return 200;
        default:
            return TAPPING_TERM;
    }
};