#pragma once

/* RGBLIGHT configuration */
#define WS2812_DI_PIN A9
#define RGBLIGHT_LED_COUNT 2
#define RGBLIGHT_LED_MAP { 1, 0 }
#define RGBLED_SPLIT { 1, 1 }
#define RGBLIGHT_LAYERS
#define RGBLIGHT_MAX_LAYERS 9

#define USB_VBUS_PIN A10
#undef  SPLIT_USB_DETECT

// > CUSTOM < //

// RGB (SINGLE KEY XD)
//#define RGBLIGHT_ANIMATIONS (deprecated)
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_BREATHE_MAX 255
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE	

#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_ALTERNATING
	
// TAP-HOLD DELAY
#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY

// ENABLING UNICODE CHARACTERS
#define UNICODE_KEY_LNX KC_RIGHT_ALT
